name: 合并并验证直播源

on:
  schedule:
    - cron: '0 0 */7 * *'  # 每7天自动运行
  workflow_dispatch:        # 支持手动触发

jobs:
  merge-and-validate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Create output directory
        run: mkdir -p output
        
      - name: Install dependencies (ffmpeg)
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Download and merge sources
        env:
          SOURCE_URLS: |
            https://cdn.jsdelivr.net/gh/ljf9096/ds@main/henan.txt
            https://cdn.jsdelivr.net/gh/a2256569/tv@main/sdzb.txt
            https://gitee.com/qttv/tv/raw/master/qt.m3u
        run: |
          > output/raw.txt
          for url in $(echo "$SOURCE_URLS" | tr '\n' ' '); do
            echo "Downloading: $url"
            temp_file=$(mktemp)
            if curl -sSL "$url" -o "$temp_file"; then
              file_ext=$(echo "$url" | awk -F. '{print tolower($NF)}')
              echo "# Source: $url" >> output/raw.txt
              [ "$file_ext" = "m3u" ] && sed '1,2d' "$temp_file" >> output/raw.txt || cat "$temp_file" >> output/raw.txt
            else
              echo "⚠️ Failed to download: $url"
            fi
            rm "$temp_file"
          done
          sort -u output/raw.txt > output/unsorted.txt

      - name: Validate links
        run: |
          # 提取所有URL（忽略注释行和空行）
          grep -E '^[^#]' output/unsorted.txt | grep -v '^$' > output/urls_to_check.txt
          
          # 验证函数（超时5秒）
          validate_url() {
            if ffmpeg -loglevel error -probesize 32 -analyzeduration 0 -timeout 5000000 -i "$1" -f null - 2>/dev/null; then
              echo "$1" >> output/valid.txt
              echo "✅ Valid: $1"
            else
              echo "❌ Invalid: $1" >> output/invalid.log
            fi
          }
          export -f validate_url
          
          > output/valid.txt
          > output/invalid.log
          cat output/urls_to_check.txt | xargs -P 4 -I {} bash -c 'validate_url "{}"'
          
          # 保留原始注释和有效链接
          grep '^#' output/unsorted.txt > output/comments.txt
          cat output/comments.txt output/valid.txt | sort -u > output/final.txt
          echo "验证结果：有效 $(wc -l < output/valid.txt) 条，无效 $(wc -l < output/invalid.log) 条"

      - name: Commit results
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add output/
          git commit -m "自动更新：$(date +'%Y-%m-%d') 有效源 $(wc -l < output/valid.txt) 条" || echo "无变更"
          git push
